FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

# Запускаем точно твой скрипт start, но можно добавить watch для удобства
# Если не хочешь менять ничего — оставляем npm start
CMD ["npm", "start"]